name: miniproyectos_en_dart
description: >
  Este repositorio está dedicado a la práctica y exploración del lenguaje de programación Dart, a través de una serie de pequeños proyectos diseñados inicialmente para ser ejecutados en una interfaz de línea de comandos (CLI) y posteriormente reescritos como aplicaciones gráficas utilizando Flutter.
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true